import fs from "node:fs";
import path from "node:path";

const ICONS_DIR = path.join(process.cwd(), "icons");
const REGISTRY_COMPONENTS_PATH = path.join(
  process.cwd(),
  "scripts",
  "registry-components.ts"
);

const TSX_RE = /\.tsx$/;
const COMPONENT_NAME_RE = /^\s{4}name: "([^"]+)",$/gm;

const HEADER = `import path from "node:path";
import { fileURLToPath } from "node:url";

import type { Schema } from "./registry-schema";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

type ComponentDefinition = Partial<
  Pick<
    Schema,
    | "dependencies"
    | "devDependencies"
    | "registryDependencies"
    | "cssVars"
    | "tailwind"
    | "title"
    | "description"
    | "author"
    | "css"
    | "envVars"
    | "docs"
    | "categories"
    | "meta"
  >
> & {
  name: string;
  path: string;
};

// This file is generated by \`pnpm gen-cli\`. Do not edit it by hand.
export const components: ComponentDefinition[] = [
`;

const getIconNames = (): string[] =>
  fs
    .readdirSync(ICONS_DIR)
    .filter((file) => file.endsWith(".tsx"))
    .map((file) => file.replace(TSX_RE, ""))
    .sort((a, b) => a.localeCompare(b));

const renderComponent = (name: string): string => `  {
    name: "${name}",
    path: path.join(__dirname, "../icons/${name}.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
`;

const syncRegistryComponents = () => {
  console.log("🔄 Syncing registry components...");

  const names = getIconNames();
  const next = `${HEADER}${names.map(renderComponent).join("")}];\n`;

  const previous = fs.existsSync(REGISTRY_COMPONENTS_PATH)
    ? fs.readFileSync(REGISTRY_COMPONENTS_PATH, "utf8")
    : "";

  if (previous === next) {
    console.log(`✅ Registry components up to date (${names.length} icons)\n`);
    return;
  }

  const previousNames = [...previous.matchAll(COMPONENT_NAME_RE)].map(
    (match) => match[1]
  );
  const previousSet = new Set(previousNames);
  const nextSet = new Set(names);

  const added = names.filter((name) => !previousSet.has(name));
  const removed = [...previousSet].filter((name) => !nextSet.has(name));
  const duplicates = previousNames.length - previousSet.size;

  fs.writeFileSync(REGISTRY_COMPONENTS_PATH, next);

  for (const name of added) {
    console.log(`   + ${name}`);
  }
  for (const name of removed) {
    console.log(`   - ${name} (icon file no longer exists)`);
  }
  if (duplicates > 0) {
    console.log(`   ~ removed ${duplicates} duplicate entr(ies)`);
  }
  console.log(`✅ Registry components synced (${names.length} icons)\n`);
};

syncRegistryComponents();
